{
 "title": "Delivery Telemetry - Professional Monitor",
 "refresh": "5s",
 "panels": [
  {
   "title": "Total de Mensagens",
   "type": "stat",
   "gridPos": { "h": 6, "w": 6, "x": 0, "y": 0 },
   "targets": [
    {
     "expr": "sum(kafka_topic_partition_current_offset{topic=\"delivery-positions\"})"
    }
   ]
  },
  {
   "title": "Brokers Ativos",
   "type": "stat",
   "gridPos": { "h": 6, "w": 6, "x": 6, "y": 0 },
   "targets": [
    { "expr": "kafka_brokers" }
   ]
  },
  {
   "title": "Tamanho do Log (Bytes)",
   "type": "stat",
   "gridPos": { "h": 6, "w": 6, "x": 12, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "decbytes" } },
   "targets": [
    {
     "expr": "sum(kafka_topic_partition_current_offset - kafka_topic_partition_oldest_offset) * 100"
    }
   ]
  },
  {
   "title": "Saúde da Replicação",
   "type": "stat",
   "gridPos": { "h": 6, "w": 6, "x": 18, "y": 0 },
   "targets": [
    {
     "expr": "sum(kafka_topic_partition_under_replicated_partition)"
    }
   ]
  },
  {
   "title": "Velocidade de Ingestão (Mensagens/Seg)",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 6 },
   "targets": [
    {
     "expr": "sum(irate(kafka_topic_partition_current_offset{topic=\"delivery-positions\"}[1m]))",
     "legendFormat": "Velocidade"
    }
   ]
  },
  {
   "title": "Distribuição por Partição",
   "type": "piechart",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 6 },
   "targets": [
    {
     "expr": "sum(kafka_topic_partition_current_offset{topic=\"delivery-positions\"}) by (partition)",
     "legendFormat": "Partição {{partition}}"
    }
   ]
  },
  {
   "title": "Atraso do Consumidor (Lag)",
   "type": "timeseries",
   "description": "Se essa linha subir muito, o sistema está lento para processar as entregas!",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 14 },
   "targets": [
    {
     "expr": "sum(kafka_consumergroup_lag{topic=\"delivery-positions\"}) by (group)",
     "legendFormat": "Grupo: {{group}}"
    }
   ]
  }
 ]
}